version: "3.7"

services:
  car_register_db:
    image: postgres
    container_name: car_register_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker123
      - POSTGRES_DB=car_register
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  app:
    build: .
    container_name: rentx
    ports:
      - 4000:4000
    volumes:
      - .:/usr/app
    network_mode: host

volumes:
  pgdata:
    driver: local
